# Generated by Django 4.2.19 on 2025-05-30 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestsneakers', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mainbanner',
            name='image',
            field=models.ImageField(upload_to='main_image/', verbose_name='Изображение баннера'),
        ),
    ]
