# Generated by Django 4.2.19 on 2025-06-06 16:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bestsneakers', '0002_alter_mainbanner_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sneaker',
            name='image',
        ),
        migrations.CreateModel(
            name='SneakerImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='sneakers/', verbose_name='Изображение')),
                ('is_main', models.BooleanField(default=False, verbose_name='Основное изображение')),
                ('sneaker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='bestsneakers.sneaker', verbose_name='Кроссовок')),
            ],
            options={
                'verbose_name': 'Изображение кроссовка',
                'verbose_name_plural': 'Изображения кроссовок',
            },
        ),
    ]
