# Generated by Django 4.2.19 on 2025-06-15 16:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestsneakers', '0003_remove_sneaker_image_sneakerimage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Рейтинг не может быть меньше 1.'), django.core.validators.MaxValueValidator(5, message='Рейтинг не может быть больше 5.')], verbose_name='Рейтинг'),
        ),
    ]
