# Generated by Django 4.2.19 on 2025-06-23 09:51

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bestsneakers', '0005_order_address_order_full_name_order_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='elexam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название экзамена')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('exam_date', models.DateField(verbose_name='Дата проведения экзамена')),
                ('image', models.ImageField(upload_to='exam_images/', verbose_name='Изображение задания')),
                ('is_public', models.BooleanField(default=False, verbose_name='Опубликовано')),
                ('participants', models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Участники экзамена')),
            ],
        ),
    ]
